name: Validate

on:
  push:
  pull_request:

jobs:
  validate-hassfest:
    runs-on: ubuntu-latest
    name: Hassfest validation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master

  validate-hacs:
    runs-on: ubuntu-latest
    name: HACS validation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration